apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-role-binding
subjects:
- kind: User  
  name: syeda.muskan1321@gmail.com
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io